ControleDeContatos/Controllers/UsuarioController.cs
using ControleDeContatos.Models;
using ControleDeContatos.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace ControleDeContatos.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepositorio _usuarioRepositorio;

        public UsuarioController(IUsuarioRepositorio usuarioRepositorio)
        {
            _usuarioRepositorio = usuarioRepositorio;
        }

        public IActionResult Index()
        {
            List<UsuarioModel> usuarios = _usuarioRepositorio.BuscarTodos();

            return View(usuarios);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(id);
            return View(usuario);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            UsuarioModel usuario = _usuarioRepositorio.BuscarPorId(id);
            return View(usuario);
        }

        public IActionResult Apagar(int id)
        {
            try
            {
                bool apagado = _usuarioRepositorio.Apagar(id);

                if (apagado)
                {
                    TempData["MensagemSucesso"] = "Usuário apagado com sucesso!";
                }
                else
                {
                    TempData["MensagemErro"] = "Ops, não conseguimos apagar seu usuário!";
                }

                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu usuário, tente novamente, mais detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Criar(UsuarioModel usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    usuario = _usuarioRepositorio.Adicionar(usuario);
                    TempData["MensagemSucesso"] = "Usuário cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(usuario);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar seu usuário, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Editar(UsuarioSemSenhaModel usuarioSemSenhaModel)
        {
            try
            {
                UsuarioModel usuario = null;

                if (ModelState.IsValid)
                {
                    usuario = new UsuarioModel()
                    {
                        Id = usuarioSemSenhaModel.Id,
                        Nome = usuarioSemSenhaModel.Nome,
                        Login = usuarioSemSenhaModel.Login,
                        Email = usuarioSemSenhaModel.Email,
                        Perfil = usuarioSemSenhaModel.Perfil

                    };

                    usuario = _usuarioRepositorio.Atualizar(usuario);
                    TempData["MensagemSucesso"] = "Usuário alterado com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(usuario);
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar seu usuário, tente novamente, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ControleDeContatos/Views/Usuario/ApagarConfirmacao.cshtml
@model UsuarioModel
@{
    ViewData["Title"] = "Confirmação apagar o usuário";
}
<div class="text-center">
    <h3>Realmente deseja apagar o usuário (@Model.Nome)?</h3>
</div>

<a class="btn btn-primary d-block w-100" asp-controller="Usuario" asp-action="Index" role="button">Cancelar exclusão</a>
<a class="btn btn-danger d-block w-100" asp-controller="Usuario" asp-route-id="@Model.Id" asp-action="Apagar" role="button">Confirmar exclusão</a>

ControleDeContatos/Views/Usuario/Criar.cshtml
@using ControleDeContatos.Enums;
@model UsuarioModel
@{
    ViewData["Title"] = "Criar usuário";
}

<div class="text-center">

    <h1 class="display-4">Cadastrar usuário</h1>

</div>

<form asp-controller="Usuario" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do usuário">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Digite o login do usuário">
        @Html.ValidationMessageFor(x => x.Login)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do usuário">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">Perfil</label>

        <select asp-for="Perfil" class="form-control">
            <option value="0">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Padrao">Padrão</option>
        </select>
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">Senha</label>
        <input type="password" asp-for="Senha" class="form-control" placeholder="Digite a senha do usuário">
        @Html.ValidationMessageFor(x => x.Senha)
    </div>

    <button type="submit" class="btn btn-primary d-block w-100">Adicionar</button>
    <a class="btn btn-secondary d-block w-100" asp-controller="Usuario" asp-action="Index" role="button">Voltar</a>
</form>

ControleDeContatos/Views/Usuario/Editar.cshtml
@using ControleDeContatos.Enums;
@model UsuarioModel
@{
    ViewData["Title"] = "Editar usuário";
}

<div class="text-center">

    <h1 class="display-4">Editar usuário</h1>

</div>

<form asp-controller="Usuario" asp-action="Editar" method="post">

    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="nome" class="form-label">Nome</label>
        <input type="text" asp-for="Nome" class="form-control" placeholder="Digite o nome do usuário">
        @Html.ValidationMessageFor(x => x.Nome)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">Login</label>
        <input type="text" asp-for="Login" class="form-control" placeholder="Digite o login do usuário">
        @Html.ValidationMessageFor(x => x.Login)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" placeholder="Digite o e-mail do usuário">
        @Html.ValidationMessageFor(x => x.Email)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">Perfil</label>
        <select asp-for="Perfil" class="form-control">
            <option value="">Selecione</option>
            <option value="@PerfilEnum.Admin">Administrador</option>
            <option value="@PerfilEnum.Padrao">Padrão</option>
        </select>
        @Html.ValidationMessageFor(x => x.Perfil)
    </div>

    <button type="submit" class="btn btn-primary d-block w-100">Editar</button>
    <a class="btn btn-secondary d-block w-100" asp-controller="Usuario" asp-action="Index" role="button">Voltar</a>
</form>

ControleDeContatos/Views/Usuario/Index.cshtml
@model List<UsuarioModel>
@{
    ViewData["Title"] = "Listagem de Usuários";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Usuario" asp-action="Criar">Adicionar novo usuário</a>
    </div>

    <br />

    @if(TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dimiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dimiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    } 

    <br />

    <h1 class="display-4">Listagem de usuários</h1>

    <table id="table-usuarios" class="display" style="width:100%">
        <thead>
            <tr">
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Login</th>
                <th scope="col">Email</th>
                <th scope="col">Perfil</th>
                <th scope="col">Data de cadastro</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if(Model != null && Model.Any())
            {
                foreach (var usuario in Model)
                {
                    <tr>
                        <th scope="row">@usuario.Id</th>
                        <td>@usuario.Nome</td>
                        <td>@usuario.Login</td>
                        <td>@usuario.Email</td>
                        <td>@(usuario.Perfil == ControleDeContatos.Enums.PerfilEnum.Admin ? "Administrador" : "Padrão")</td>
                        <td>@usuario.DataCadastro</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger" asp-route-id="@usuario.Id" asp-controller="Usuario" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum usuário encontrado</td></tr>
            }
        </tbody>
    </table>
</div>